# -*- coding: utf-8 -*-
"""C118 Clustering Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZdxiWPNB2tjN-Pabusz6iqu4tgv3MLFI

# Project on Clustering

Here is some data from ISRO about Interstellar Objects. Isro has identified a few interstellar objects, and they could determine the size of these bodies and the light that they emit.

\
We have the data where the size of these objects is in (Thousand Miles), so a size 1 represents 1 Thousand Miles in Diameter. We also know the light that these bodies emit in the microlux unit, which is a unit to measure the intensity of light.

\
Can you find the clusters to identify how many types of bodies did ISRO find?
"""

#Uploading the csv
from google.colab import files
data_to_load = files.upload()

import pandas as pd
import plotly.express as px

df = pd.read_csv("data.csv")

print(df.head())

fig = px.scatter(df, x="Size", y="Light")
fig.show()

""" Finding the best K value by using the WCSS perimeter"""

from sklearn.cluster import KMeans

X = df.iloc[:, [0, 1]].values

print(X)

wcss = []
for i in range(1, 11):
    kmeans = KMeans(n_clusters=i, init='k-means++', random_state = 42)
    kmeans.fit(X)
    # inertia method returns wcss for that model
    wcss.append(kmeans.inertia_)

"""using elbow method finiding the k values."""

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10,5))
sns.lineplot(range(1, 11), wcss, marker='o', color='red')
plt.title('The Elbow Method')
plt.xlabel('Number of clusters')
plt.ylabel('WCSS')
plt.show()

"""Finding the proper cluster points and plotting the graph."""

kmeans = KMeans(n_clusters = 3, init = 'k-means++', random_state = 42)
y_kmeans = kmeans.fit_predict(X)

plt.figure(figsize=(15,7))
sns.scatterplot(X[y_kmeans == 0, 0], X[y_kmeans == 0, 1], color = 'yellow', label = 'Cluster 1')
sns.scatterplot(X[y_kmeans == 1, 0], X[y_kmeans == 1, 1], color = 'blue', label = 'Cluster 2')
sns.scatterplot(X[y_kmeans == 2, 0], X[y_kmeans == 2, 1], color = 'green', label = 'Cluster 3')
sns.scatterplot(kmeans.cluster_centers_[:, 0], kmeans.cluster_centers_[:, 1], color = 'red', label = 'Centroids',s=100,marker=',')
plt.grid(False)
plt.title('Clusters of Interstellar Objects')
plt.xlabel('Size')
plt.ylabel('Light')
plt.legend()
plt.show()

"""The Yellow ones are the meteorites and other interstellar objects.

\
The Green ones are the Planets.

\
The Blue ones are the Stars.
"""

